---
- name: Ensure libselinux-python is installed.
  yum: 
    name: libselinux-python

- name: Check the selinux status.
  command: getenforce
  register: result
  changed_when: False

- name: Ensure selinux is disabled.
  command: setenforce 0
  when: ("Disabled" not in result.stdout) and ("Permissive" not in result.stdout)

- name: Ensure selinux is disabled permanently.
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX=.*"
    line: "SELINUX=disabled"