---
# selinux
- name: Ensure libselinux-python is installed.
  yum: name=libselinux-python

- name: Check the selinux status.
  command: getenforce
  register: result
  changed_when: False

- name: Ensure selinux is disabled.
  command: setenforce 0
  when: ("Disabled" not in result.stdout) and ("Permissive" not in result.stdout)

- name: Ensure selinux is disabled permanently.
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX=.*"
    line: "SELINUX=disabled"

# NetworkManager
- name: Ensure NetworkManager is stopped and disabled to start at boot.
  service: name=NetworkManager state=stopped enabled=no
  when: init_networkmanager_enable != true and ansible_distribution_major_version == "7"

# repositories
- name: Ensure repository {{ item }} is installed.
  yum: name={{ item }}
  with_items:
    - epel-release
    - http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm

- name: Fix EPEL repository only RHEL6.
  replace: dest=/etc/yum.repos.d/epel.repo regexp="mirrorlist=https" replace="mirrorlist=http"
  when: ansible_distribution_major_version == "6"

- name: Ensure repository {{ item }} is disabled.
  replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
    - remi.repo
    - remi-safe.repo

# packages
- name: Ensure useful packages are installed.
  yum: name={{ item }}
  with_items:
    - git
    - sudo
    - wget
    - nmap
    - zsh
    - screen

- name: Ensure htop is installed
  yum: name=htop enablerepo=epel

- name: Ensure build packages are intalled.
  yum: name={{ item }}
  with_items:
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc
    - gcc-c++
    - make
    - pkgconfig
    - unzip

# root user
- name: Ensure only the administrator can become a root.
  lineinfile:
    dest: /etc/pam.d/su
    regexp: "^.*auth.*required.*pam_wheel.so use_uid"
    line: "auth		required	pam_wheel.so use_uid"

- name: Ensure sudo without the only wheel group.
  lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults.*requiretty"
    line: "Defaults:%wheel    !requiretty"

- name: Edit sudo secure path.
  lineinfile:
    dest: /etc/sudoers
    regexp: "^Defaults    secure_path.*"
    line: "Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin"

# shell
- name: Ensure default shell is zsh.
  command: chsh -s /bin/zsh
  register: result
  changed_when: '"Shell not changed" not in result.stderr'
  when: lookup('env', 'SHELL') != '/bin/zsh'

# cron
- name: Ensure cronie-anacron is removed.
  yum: name=cronie-anacron state=absent
  when: ansible_distribution_major_version == "7"

- name: Ensure cronie-noanacron is installed.
  yum: name=cronie-noanacron
  when: ansible_distribution_major_version == "7"

- name: Ensure cronie-noanacron is started and enabled to start at boot.
  service: name=crond state=started enabled=yes
  when: ansible_distribution_major_version == "7"
